name: Comment and Increment Version

on: [push]

jobs:
  process-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Comment lines with specific comment
        run: |
          python comment_lines.py

      - name: Increment version
        run: |
          python increment_version.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m 'Process code: Comment lines and increment version'
          git push
